name: news_app_demo_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # run command flutter gen-l10n
  intl: 0.20.2
  flutter_localizations: # <--- Make sure this is here!
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_riverpod: ^3.0.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  http: ^1.6.0
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - lib/l10n/
    - .env
  fonts:
    - family: Noto Sans Khmer
      fonts:
        - asset: assets/fonts/NotoSansKhmer-Regular.ttf
        - asset: assets/fonts/NotoSansKhmer-Bold.ttf
          weight: 700